### ISSUE TITLE
The Last Express OG DOS ver.

### ISSUE THREAD

**Issue by suird** [m-lohmann/GOG-only_games#13]
AFAIK GOG is the only place you can buy the original DOS version of The Last Express, Steam and prob most other stores only sell the "Gold Edition" remake by Dotemu.

https://www.gog.com/game/last_express_the?utm_campaign=adtraction&utm_medium=affiliate&utm_source=adtraction&r=true

https://store.steampowered.com/app/252710/?utm_source=PCGamingWiki&utm_medium=PCGamingWiki&utm_campaign=PCGamingWiki

**Comment by m-lohmann** [comment]
Thanks for your help!

It would be awesome to post these contributions as pull requests instead of posting issues. This way I can simply review the request and confirm the change ;)
