### ISSUE TITLE
Dungeons & Dragons: Gold Box Classics are available on Steam

### ISSUE THREAD

**Issue by straw-son** [m-lohmann/GOG-only_games#15]
I'm not sure if there's a difference between GOG and Steam versions, but it seems like all the [Gold Box Classics are actually available on Steam](https://store.steampowered.com/curator/42184283).

**Comment by m-lohmann** [comment]
Thanks for the hint, mate!

If you find info like this it would be awesome to actually add the relevant changes to the document itself (with the edit function) and post a pull request. This way I can simply confirm the request or apply necessary corrections easily.
I often don’t have much time to add stuff that’s posted as issues—I have to check and manually add all the findings myself, which can be a time consuming process.
