### ISSUE TITLE
Add Stranglehold

### ISSUE THREAD

**Issue by russbus64** [m-lohmann/GOG-only_games#18]
AKA John Woo Presents Stranglehold. This title is only available on GOG, as far as I know.

https://www.gog.com/game/stranglehold?pp=2863d7ae605104eeef364e3f164d3404e20f680c

**Comment by m-lohmann** [comment]
I added the game—albeit a little late ;)
Feel free to add the changes by yourself. That way I can simply approve the additions or changes which makes it a bit easier.

Thanks for your help! I really appreciate every contribution.
