### ISSUE TITLE
Legacy of Kain: Soul Reaver was delisted

### ISSUE THREAD

**Issue by Drejzer** [m-lohmann/GOG-only_games#20]
LoK:Soul Reaver was delisted from pretty much everywhere quite a while ago.

**Comment by Settyness** [comment]
It looks like they're possibly reserving the Steam page for the [upcoming remasters](https://www.thesixthaxis.com/2024/07/27/legacy-of-kain-soul-reaver-i-ii-remastered-leaked-by-merch/). I made a [pull request](https://github.com/m-lohmann/GOG-only_games/pull/22) regarding  this.

![Screenshot_2024-09-22_21-55-31](https://github.com/user-attachments/assets/b7a76aac-a4e5-4e56-ae16-095dc81075b5)

**Comment by m-lohmann** [comment]
I merged Settyness’ pull request. Thanks for your help!
