### ISSUE TITLE
Battle.net Now Has Classic Offerings

### ISSUE THREAD

**Issue by Settyness** [m-lohmann/GOG-only_games#21]
To my surprise, [Diablo + Hellfire](https://us.shop.battle.net/en-us/family/diablo), [WarCraft: Orcs & Humans](https://us.shop.battle.net/en-us/family/warcraft), and [WarCraft II: Battle.net Edition](https://us.shop.battle.net/en-us/family/warcraft-ii) are now available for purchase via Battle.net. However, I have noticed that Battle.net is _not_ included under **Platforms this list is checked against**. I could submit a PR regarding this, but I thought I'd make an issue first to see how you'd prefer to proceed.

EDIT: I've since opened an unrelated PR and can tack-on whatever changes deemed fit from this discussion.

**Comment by m-lohmann** [comment]
I have no problem adding more platforms, if you guys check against them. I’m buried under work at the moment and don’t have much time to do all the checks myself.

Feel free to submit your PRs! I’m glad that my list is kept up to date and read by a growing amount of gog users. Thank you all for your work, I really appreciate it!
